### PR TITLE
Changed creativecloud.sh to work with CC 2018

### PR DESCRIPTION
**Pull request by tristan20**
Added newer installer, use winetricks for dependencies as POL scripts do not seem to work at least for corefonts.
The Login window of the CC App loads a little slow. Tested Lightroom and Photoshop CC 2018 and both seem to work with no problems.

### CODE REVIEW

**Comment by corbindavenport** [comment]
Oh wow, I had no idea you could directly pull winetricks instead of using POL's alternatives. This will help a lot when porting the script to vanilla Wine, too. Once I test this on my VM, I'll merge it.

**Comment by corbindavenport** [comment]
Also @tristan20, have you tested switching out the Wine version for anything newer? I wonder if the latest v3.0 might fix some lingering bugs.

**Comment by tristan20** [comment]
@corbindavenport I did not get Wine 3.0 working but I did only try very briefly. However 64 bit Photoshop did install with Wine 2.20, although the installer crashed a couple times before it went through.
I did not have any Problems with the 32-bit installer and Wine 2.20.

**Comment by corbindavenport** [comment]
Ok, I tested this on my Ubuntu VM and I'm only seeing minor issues (like the Creative Cloud app seems to get stuck sometimes). Still, this is a major improvement. I'll merge this and see if I can fix any lingering bugs, then merge to master.

**Pull request merged**
